"""
D2 (constitution v2 §2, "time-stepping is fast-forwardable"): the discrete
constant-coefficient advection-diffusion operator on a uniform periodic
grid is circulant, hence exactly diagonalized by the DFT, so advancing to
ANY time T costs O(log^2 N) gates (QFT, diagonal phase/decay, inverse
QFT) independent of T and with no CFL constraint.

This module builds the discrete operator explicitly, verifies it is
circulant, verifies the DFT diagonalizes it with the expected eigenvalues
(the semi-discrete dispersion relation), and verifies that applying it via
diagonal multiplication in Fourier space reproduces exp(t*A) for
arbitrary t -- i.e. fast-forwarding -- to machine precision, at O(1) cost
in t.
"""
import numpy as np


def advection_diffusion_operator(N: int, Uc: float, nu: float, domain_length: float):
    """
    1D periodic advection-diffusion operator A such that du/dt = A u,
    using a 2nd-order central difference for advection and diffusion on
    N equally spaced points. Returns the dense N x N matrix (only used
    for small N in tests/verification -- production code never forms
    this densely).
    """
    dx = domain_length / N
    A = np.zeros((N, N))
    for i in range(N):
        ip1 = (i + 1) % N
        im1 = (i - 1) % N
        # advection: -Uc * du/dx  (central)
        A[i, ip1] += -Uc / (2 * dx)
        A[i, im1] += Uc / (2 * dx)
        # diffusion: nu * d2u/dx2
        A[i, ip1] += nu / dx**2
        A[i, im1] += nu / dx**2
        A[i, i] += -2 * nu / dx**2
    return A


def is_circulant(A: np.ndarray, tol=1e-10) -> bool:
    """A is circulant iff every row is the previous row cyclically shifted
    by one."""
    N = A.shape[0]
    for i in range(1, N):
        if not np.allclose(A[i], np.roll(A[0], i), atol=tol):
            return False
    return True


def dft_eigenvalues(A: np.ndarray) -> np.ndarray:
    """
    Eigenvalues of the circulant matrix A generated by row c = A[0], with
    A[i,j] = c[(j-i) mod N] (i.e. row i is row 0 rolled right by i -- see
    is_circulant). Eigenvector v_k[n] = exp(2j*pi*k*n/N) has eigenvalue

        lambda_k = sum_m c[m] * exp(2j*pi*k*m/N) = N * ifft(c)[k]

    NOT fft(c)[k] -- that sign gives the eigenvalues of the transposed
    (correlation-vs-convolution) operator and silently mismatches by a
    conjugation. Verified against `analytic_dispersion` and against
    `np.linalg.eigvals` in tests/test_d2_fastforward.py.
    """
    N = A.shape[0]
    return N * np.fft.ifft(A[0])


def analytic_dispersion(N: int, Uc: float, nu: float, domain_length: float) -> np.ndarray:
    """
    Expected eigenvalue of mode k for the central-difference operator:
      lambda_k = -i*Uc*sin(k*dx)/dx + nu*(2*cos(k*dx) - 2)/dx^2
    for k = 2*pi*m/domain_length, m = 0..N-1 (wavenumbers in FFT order).
    """
    dx = domain_length / N
    m = np.fft.fftfreq(N, d=1.0 / N)  # integer wavenumber index in FFT order
    k = 2 * np.pi * m / domain_length
    lam = -1j * Uc * np.sin(k * dx) / dx + nu * (2 * np.cos(k * dx) - 2) / dx**2
    return lam


def fast_forward_apply(u0: np.ndarray, eigvals: np.ndarray, t: float) -> np.ndarray:
    """
    Apply exp(t*A) to u0 via the DFT diagonalization: FFT, multiply by
    exp(t*lambda_k), inverse FFT. Cost is O(N log N) classically /
    O(log^2 N) gates quantumly (QFT + diagonal phase/decay + inverse
    QFT), and is INDEPENDENT of t -- a single call reaches any T.
    """
    u0_hat = np.fft.fft(u0)
    u_hat = u0_hat * np.exp(t * eigvals)
    return np.fft.ifft(u_hat)
